### ISSUE TITLE
Doesn't work with typescript projects

### ISSUE THREAD

**Issue by marcofugaro** [observablehq/prettier-react-tachyons#10]
![image](https://user-images.githubusercontent.com/7217420/53172775-73057b00-35e6-11e9-86a1-1f74379bf4e4.png)

probable because the babel parser is not correctly configured, the default prettier parser works fine

**Comment by tmcw** [comment]
Yep, it's not intended to work with typescript projects. Prettier itself [uses typescript’s parser](https://github.com/prettier/prettier/blob/master/src/language-js/parser-typescript.js) to parse TypeScript, rather than Babel, and implementing compatibility would be an undertaking. PRs accepted to this end, but closing this issue because it's not in the current project scope.

**Comment by marcofugaro** [comment]
@tmcw what's the challenge of using `@typescript-eslint/typescript-estree`?

**Comment by tmcw** [comment]
I don't know offhand, I've never tried it. You're welcome to try it out and contribute a PR implementing the addition.

**Comment by marcofugaro** [comment]
Sure! Will make a PR!
