### ISSUE TITLE
This is awesome! 💥

### ISSUE THREAD

**Issue by caesarsol** [observablehq/prettier-react-tachyons#2]
Just a token of appreciation from Accurat developers team 😄 

Do you have any idea if it would be difficult to implement as an `eslint` plugin?

**Comment by tmcw** [comment]
Thanks, I appreciate it! And, yep, it'd be feasible to convert it into an eslint plugin - the same core that parses, deduplicates, and rearranges classes would become an assertion instead of an assignment, and you would [create a rule](https://eslint.org/docs/developer-guide/working-with-rules) if the cleaned classes don't match the code in place.

Go for it if you want to go the eslint route, and let me know if you end up doing so. We're pretty happy with prettier doing any kind of non-opinionated style changes, so we'll probably stick with this and other cleanup tasks being automated instead of checked.

**Comment by Bebersohl** [comment]
I made an eslint-plugin if anyone wants to go the linting route:

https://github.com/Bebersohl/eslint-plugin-tachyons-jsx
